### ISSUE TITLE
数回に一回テストが落ちる．

### ISSUE THREAD

**Issue by MaxMEllon** [MaxMEllon/comelon#17]
エラー内容は以下のとおり

```
  1) MainView "before all" hook:
     Error: the string "notlogin" was thrown, throw an Error :)
      at Runner.fail (node_modules/.store/mocha@2.4.5/_/lib/runner.js:226:11)
      at Runner.uncaught (node_modules/.store/mocha@2.4.5/_/lib/runner.js:700:8)
      at process.uncaught (node_modules/.store/mocha@2.4.5/_/lib/runner.js:783:10)

  2) MainView Uncaught error outside test suite:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
      at node_modules/.store/mocha@2.4.5/_/lib/runner.js:536:27
      at Runner.runTest (node_modules/.store/mocha@2.4.5/_/lib/runner.js:424:5)
      at node_modules/.store/mocha@2.4.5/_/lib/runner.js:533:12
      at next (node_modules/.store/mocha@2.4.5/_/lib/runner.js:342:14)
      at node_modules/.store/mocha@2.4.5/_/lib/runner.js:352:7
      at next (node_modules/.store/mocha@2.4.5/_/lib/runner.js:284:14)
      at Immediate._onImmediate (node_modules/.store/mocha@2.4.5/_/lib/runner.js:320:5)
```

**Comment by MaxMEllon** [comment]
テストの時のログインの非同期処理async/awaitにするのわすれてたわ

**Comment by MaxMEllon** [comment]
Socket作るときのportが>= 0 and < 65536じゃないってnet.jsが怒ってる．

**Comment by MaxMEllon** [comment]
ログインの非同期を待ったことで

```
  1) MainView "before all" hook:
     Error: the string "notlogin" was thrown, throw an Error :)
      at Runner.fail (node_modules/.store/mocha@2.4.5/_/lib/runner.js:226:11)
      at Runner.uncaught (node_modules/.store/mocha@2.4.5/_/lib/runner.js:700:8)
      at process.uncaught (node_modules/.store/mocha@2.4.5/_/lib/runner.js:783:10)
```

は解消．
ログイン後，nsen/hotaruに接続を試みると，時々

```
    // Uncaught RangeError: port should be >= 0 and < 65536: 
    //   at lookupAndConnect (net.js:930:13)
    //   at Socket.connect (net.js:907:5)
    //   at Object.exports.connect.exports.createConnection (net.js:64:35)
    //   at node_modules/.store/nicolive@0.0.4/_/lib/nicolive/view.js:37:26
    //   at Request._callback (node_modules/.store/nicolive@0.0.4/_/lib/nicolive/get-player-status.js:71:14)
    //   at Request.self.callback (node_modules/.store/request@2.69.0/_/request.js:199:22)
    //   at Request.<anonymous> (node_modules/.store/request@2.69.0/_/request.js:1036:10)
    //   at IncomingMessage.<anonymous> (node_modules/.store/request@2.69.0/_/request.js:963:12)
    //   at endReadableNT (_stream_readable.js:906:12) 
```

**Comment by MaxMEllon** [comment]
async/awaitしても，dispatchされてstoreにされるまで待つのではなく，イベントの発火までしか待たないのでダメ．正確にやろうとすると，Dispatcherにdispatchされるまで待たないといけない．
そうすると，必然的にActionのテストではStoreをモックにする必要がでてくる．(Dispatcher.dispatchをテスト時のみ書き換えたいから）

今はめんどくさいのでsleepで対処して改善されるか様子をみる．

**Comment by MaxMEllon** [comment]
うまくイベント登録できる部分はイベント化．
外部に依存したり比較的超時間がかかるものは，setIntervaliで処理待ちを行うように．
